### ISSUE TITLE
Unable to parse simple protobuf file with imported options

### ISSUE THREAD

**Issue by marcusljx** [emicklei/proto#100]
## Code
```
        parser := proto.NewParser(bytes.NewBuffer(data))
	p, parseErr := parser.Parse()
	if parseErr != nil {
		return nil, fmt.Errorf("(*proto.Parser).Parse : %v", parseErr)
	}
```

## Contents of `data`
```
syntax = "proto3";

package myservice;

import "google/api/annotations.proto";

service MyService {
  rpc Something(Empty) returns (Empty) {
    option (google.api.http).get = '/v1/something';
  }
}

message Empty{}
```

## Error
```
(*proto.Parser).Parse : <input>:13:1: found "message" but expected [service comment|rpc]
```

**Comment by peter-edge** [comment]
Does this compile with protoc? This doesn’t look like valid Protobuf to me.

**Comment by marcusljx** [comment]
Yes I can compile this with `protoc`.

for reference
```
$ protoc --version
libprotoc 3.6.1
```

**Comment by marcusljx** [comment]
For reference, the command I used was:
```
protoc -I. -I $GOPATH/src/github.com/googleapis/googleapis myservice.proto --go_out=. 
```

**Comment by peter-edge** [comment]
The typical syntax is

{ get: “value” }

Not

.get = ‘value’

I’ve never seen that before. I’ll try compiling this later. Note I’m not a maintainer of this repo but subscribe because one of my repos uses it extensively.

**Comment by marcusljx** [comment]
https://cloud.google.com/service-infrastructure/docs/service-management/reference/rpc/google.api#httprule

The very first example uses it:
`option (google.api.http).get = "value";`

**Comment by peter-edge** [comment]
One of my least favorite part of the Protobuf syntax - there’s multiple ways to do the same thing and there’s no good documentation of all of them. Alas. Well I guess this will have to be handled.

**Comment by marcusljx** [comment]
Interestingly, this works if I use double-quotes for the literal string
```
option (google.api.http).get = "/v1/something";  // this works
```
instead of
```
option (google.api.http).get = '/v1/something';   // original; parser returns error
```

I don't think it's to do with the `.get` any more.

**Comment by marcusljx** [comment]
Upon further investigation, this is due to the usage of `text/scanner.Scanner` in the `Parser`, which is primarily used to scan golang-style syntax.

The mode used only allows for parsing of double-quoted (`"`) strings of text. Single quoted text (`'`) forces the tokenizer to set `tokEnd = tokPos + 1`, since single-quotes are reserved only for `char` types in golang and not `string`.

I'm debugging way out of my depth here, so it's mainly a shot in the dark, but I'm not confident that this can be fixed trivially.

**Comment by marcusljx** [comment]
I've made a PR with some edits to the function that handles single-quoted strings, to handle edge cases. Also added more unit test cases for these kind of situations.

Could you take a look please @emicklei ?

**Comment by peter-edge** [comment]
Is this issue fixed?

**Comment by marcusljx** [comment]
Yes, but I'm not sure if I should be the one to close the issue or not, as I'm not the maintainer.
