### ISSUE TITLE
Nested enum with inline  comments break parser

### ISSUE THREAD

**Issue by sevennt** [emicklei/proto#118]
My protobuf example:
```protobuf
// FooResponse is my response
message FooResponse {
  enum BarEnum // BarEnum is my nested enum
  {
      BAR_TYPE_INVALID= 0;
      BAR_TYPE_BAD = 1;
  }
  string msg = 1;
}
```

this file compiles with protoc, but fails parsing with this errors:
```bash
hello.proto:57:16: found "// BarEnum is my nested enum" but expected [enum opening {]
```

The `emicklei/proto` version is `v1.6.15`

**Comment by emicklei** [comment]
Thank you for reporting this and providing a failing example.

**Comment by emicklei** [comment]
this issue also applies to any element container such as message, oneof, service . I am creating tests for all of them and fixing each.

**Comment by sevennt** [comment]
@emicklei Thank you.

**Comment by emicklei** [comment]
the fix is merged, if it also works for you then you can close it.

**Comment by sevennt** [comment]
It works.
