### ISSUE TITLE
Infinite loop in Parser.Parse()

### ISSUE THREAD

**Issue by bradleyjkemp** [emicklei/proto#121]
Hi, I wrote a simple fuzzing harness and ran it for a while and it found this malformed input that causes the parser to get stuck at 100% CPU and (as far as I can tell) never exit:
```go
package main

import (
	"bytes"
	"fmt"
	"github.com/emicklei/proto"
)

var data = `syntax = "";
package mp.ub.io;

message er {
    er ue = 1;
    t4 um = 2;
}

message er {
    ng ue = 3;
    t4 um = 4;
}

message ra {
    er ue = 1;
    t4 um = 2;
    ng ld = 3;
}

service ce {
    rpc st(er) returns (er) {};
    rpc es(er) returns (stream er) {
`

func main() {
	_, err := proto.NewParser(bytes.NewBufferString(data)).Parse()
	fmt.Println("Finished", err)
}
```
Another input that triggers the same behaviour is: `package p;message r{r e=1;4m=2}message r{g e=3;4m=4}message a{r e=1;4m=2g d=3}service e{rpc t(r)returns(r){optioo`

**Comment by bradleyjkemp** [comment]
It might be interesting to set up something like https://fuzzit.dev for continuous fuzzing of this library? Parsers are a really easy thing to write fuzzing harnesses for 🙂 

This was the simple harness I used to find the above issue:
```go
package proto

import "bytes"

func Fuzz(data []byte) int {
	_, err := NewParser(bytes.NewBuffer(data)).Parse()
	if err != nil {
		return 0
	}

	return 1
}
```

Happy to help if you're interested

**Comment by emicklei** [comment]
thank you for reporting this issue.
