### ISSUE TITLE
Field type with keyword is not correctly parsed

### ISSUE THREAD

**Issue by YaseenAlk** [emicklei/proto#127]
Ran into this problem while trying to parse [this protobuf from the Envoy project](https://github.com/envoyproxy/envoy/blob/87b2e1a45a6ac9dddba90ecfe3a20022be91221a/api/envoy/config/common/tap/v2alpha/common.proto#L29), which results in the error:

`found "service" but expected [oneof closing }]`

While this issue manifested itself in the `oneof.go` parser, I believe it might apply to any parsed field.

Here's a test that can reproduce it:

```go
func TestFieldOneofImportedKeyword(t *testing.T) {
	fieldType := "service.foo.bar"
	proto := `message Value {
		oneof value {
			` + fieldType + ` value = 1;
		}
	}`
	p := newParserOn(proto)
	def := new(Proto)
	err := def.parse(p)
	if err != nil {
		t.Fatal(err)
	}
	m := def.Elements[0].(*Message)
	if len(m.Elements) != 1 {
		t.Errorf("expected one element but got %d", len(m.Elements))
	}
	o := m.Elements[0].(*Oneof)
	if len(o.Elements) != 1 {
		t.Errorf("expected one element but got %d", len(o.Elements))
	}
	f := o.Elements[0].(*OneOfField)
	if got, want := f.Type, fieldType; got != want {
		t.Errorf("got [%v] want [%v]", got, want)
	}
	if got, want := f.Name, "value"; got != want {
		t.Errorf("got [%v] want [%v]", got, want)
	}
}
```

Happy to help however I can, just wanted to bring it to your attention first and see if you had any feedback

**Comment by emicklei** [comment]
thank you for reporting this and taking the time to provide me with a test case 👍 

I will work on solution for this.

**Comment by emicklei** [comment]
it is a harder problem than i thought, my initial change fix this case but broke others :-(

**Comment by YaseenAlk** [comment]
Hey @emicklei, I took a look at the branch you made for this issue. Nice work! It fixed the problems I addressed in this issue. From what I can tell, all of the existing tests on it are passing as well - is there anything still broken as a result of the changes? Happy to help if needed
