### ISSUE TITLE
Parser parses non-valid Protobuf files

### ISSUE THREAD

**Issue by peter-edge** [emicklei/proto#14]
For example, if I leave the `;` off the end of a statement (like a package declaration, a file option, or a field), the Parser still returns a validly parsed definition. This means writing a formatter (like `protofmt`) or a linter will output something valid for non-valid Protobuf, which (especially in the linter case) means something can "pass lint" without being valid.

Example:

```
syntax = "proto3";

package foo
```

Note the pack of a `;` after the package declaration.

```
$ protofmt tmp.proto
syntax = "proto3";

package foo;
```

**Comment by peter-edge** [comment]
Another example:

```
$ cat tmp.proto
syntax = "proto3" package foo;
[~]
syntax = "proto3";

package foo;
```

**Comment by emicklei** [comment]
so I knew about this. The parser is not validating that much, like i mentioned in the other issue, it was created for a Formatter. My practice is to use protoc for finding illegal constructions.

I do like the idea of extending the package to catch more (all?) such invalid cases. Until then, it is probably best to create unit tests for your findings and get them solved. I recall there are quite a number of validations in place, just never made it complete.

**Comment by peter-edge** [comment]
OK, I'll try to tackle these one at a time as I learn the library more. I agree it would be hard to rely on this to perfectly compile Protobuf for now, but we should get there. In the mean time, I'll shell out to protoc to validate the file first.

**Comment by emicklei** [comment]
i propose to create a new package, protocheck as part of the proto-contrib repo.
