### ISSUE TITLE
Confusing comment parsing

### ISSUE THREAD

**Issue by peter-edge** [emicklei/proto#24]
When I look at `newComment`, the logic seems like it can produce inconsistent results depending on how the user specifies the comment. 

What I want:

Lines: The lines of the comment, without any `//`, no matter what
CStyle: whether the user specified this in c-style
ExtraSlash: remove this

Thoughts?

**Comment by emicklei** [comment]
The extra slash was added later because the documentation tool we uses this to separate public from private comment.
As for the Lines, I recall they do not have the slashes ? maybe it was an unintended side-effect of switching the scanner. I will have a closer look.

**Comment by peter-edge** [comment]
Closing this for now as this is more a future improvement for 2.0.
