### ISSUE TITLE
Comments associated with Visitess when newlines between the comment and Visitee

### ISSUE THREAD

**Issue by peter-edge** [emicklei/proto#26]
Example:

```
// foo

// bar

syntax = "proto3";

// baz

package bat;
```

`// bar` is the `Comment` on the `Syntax` object, and `// baz` is the `Comment` on the `Package` object. `// foo` correctly is associated with just the `Proto` object and will be hit when you get to `VisitComment` on `Proto`.

**Comment by emicklei** [comment]
This is not how the package works and thought of. Empty lines will disassociate the comment. Without this, many of our definitions will have wrong format ; e.g. syntax will have the copyright as its comment. Field comment will dangle.  
Maybe this behavior can be made optional.

**Comment by peter-edge** [comment]
This *is* how it is currently parsed, is what I am saying. Putting a newline does not disassociate the comment. In the above example, `// bar` will be the `Comment` field on `Syntax`, and `// baz` will be the `Comment` on `Package`. This is a bug if this is not how it should operate

**Comment by emicklei** [comment]
ok, i will review it again

**Comment by emicklei** [comment]
ic, the comments should not be associated because they are separated. I created a test for this to fix.

**Comment by peter-edge** [comment]
Your change here introduced a bug. Comments no longer appropriately associate.

```
$ cat yarpcproto/yarpc.proto
syntax = "proto3";

package uber.yarpc;

option go_package = "yarpcproto";

// Oneway is the return type to use for an rpc method if
// the method should be generated as oneway.
message Oneway {
  bool ack = 1;
}
```

The comment on `Oneway` is not associated with the `*proto.Message`.

Can you please revert?
