### ISSUE TITLE
Elements []Visitee and Comment/InlineComment on a given Visitee?

### ISSUE THREAD

**Issue by peter-edge** [emicklei/proto#27]
This may just need to be documented, but a `Comment` is a `Visitee`, so on `Enum` for example, you have `Elements []Visitee` and `Comment *Comment` - will the `Comment` not be in the `Elements` slice? This would make sense, and either way, we should have it documented as to the expected behavior. I may be missing something, just wanted to file this while it is in my head.

**Comment by emicklei** [comment]
That is correct, elements do not contain comment values.  Each element can have zero or one Comment. I think I made this decision to have the design simple ; no need to find the comment elements, dealing with multiple comments.
