### ISSUE TITLE
Inconsistent addition of Options field to Visitees

### ISSUE THREAD

**Issue by peter-edge** [emicklei/proto#28]
Example:

```
message Foo {
  option deprecated = true;
  int64 hello = 1;
}
```

The deprecated option is included in the `Elements []Visitee` slice on `Message` meaning you need to visit it, while in other `Visitee` structs such as `Field`, there is an `Options []*Option` slice. Related to https://github.com/emicklei/proto/issues/27.

**Comment by emicklei** [comment]
Yes, hmmm, I agree that this is inconsistent. The spec did not mention different kinds op options but appearantly they are.  It will be a breaking change to move the message options to its own slice.

**Comment by emicklei** [comment]
we could store the field options in Elements of a Field and deprecate the Options

**Comment by peter-edge** [comment]
One or the other - I like having the options separate sometimes. Just want to be consistent.

**Comment by emicklei** [comment]
in the issue42 branch, i changed this for RPC because it could not hold comments. It is not merged for me to review later again.

**Comment by peter-edge** [comment]
This is issue 28, not 42

**Comment by emicklei** [comment]
i mentioned it because it has a similar design change

**Comment by emicklei** [comment]
working towards a consistent design v2, adding extra fields for v1
