### ISSUE TITLE
error with included types and service definition

### ISSUE THREAD

**Issue by bennyscetbun** [emicklei/proto#35]
hi I would like to use your library.
But when i parse a file like this one:

```
syntax = "proto3";

package bla.protobuf.services;

import "google/protobuf/empty.proto";

service blaService {
    rpc Health(google.protobuf.Empty) returns (google.protobuf.Empty) {}
}
```

I have an error:
```
<input>:8:22: Found "." but expected [rpc type closing )].
```

Am i doing something wrong? (the file works fine with protoc)
If the issue is on your side could you fix it?
Thanks

**Comment by emicklei** [comment]
thank you for reporting this

**Comment by bennyscetbun** [comment]
thanks it fix the issue!
