### ISSUE TITLE
Comments affect right justification of options.

### ISSUE THREAD

**Issue by daroot** [emicklei/proto#4]
```syntax = "proto3";

import  "google/protobuf/timestamp.proto";
import  "github.com/gogo/protobuf/gogoproto/gogo.proto";

option       (gogoproto.marshaler_all) =  true;
option           (gogoproto.sizer_all) =  true;
option     (gogoproto.unmarshaler_all) =  true;
option (gogoproto.goproto_getters_all) = false;
option        (gogoproto.populate_all) =  true;
option           (gogoproto.equal_all) =  true;

message Msg {
                     string source    = 1; //            This affects the option on #3 ]
                     string dest      = 2; // Foo
  google.protobuf.Timestamp deadline  = 3 [(gogoproto.stdtime) = true]; // Bar
}
```

Formatting this produces a large space between the `=` and  `true` in the third line, like so:

```
  google.protobuf.Timestamp deadline = 3 [(gogoproto.stdtime) =                                         true]; // Bar
```

It appears to be considering the comments on in other fields when choosing how to align the constant in the option on the field.  I think it should only consider options in other fields, and not comments.

In particular, it only seems to do this if not every field has an option.  If all the fields have options, it does the right thing.

**Comment by emicklei** [comment]
thank you for reporting this. I will work on it after completing issue #3

**Comment by daroot** [comment]
The latest commit seems to have nailed the problem.  Nice work!
