### ISSUE TITLE
Oneof and service options not supported

### ISSUE THREAD

**Issue by peter-edge** [emicklei/proto#43]
They are valid:

https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.proto#L589
https://github.com/google/protobuf/blob/master/src/google/protobuf/unittest_custom_options.proto#L108

There may be other option types not handled, will check as I go.

Update - service options also not handled https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.proto#L632

**Comment by emicklei** [comment]
closing this as #62 has been merged.
