### ISSUE TITLE
the collector in `visitor_test` would be useful as a public object

### ISSUE THREAD

**Issue by bjohnson-va** [emicklei/proto#58]
https://github.com/emicklei/proto/blob/f046ec0808810d6e2de21ed16dc0fb05d821a10d/visitor_test.go

I'm finding, in order to use this library, I basically have to implement the collector from `visitor_test` because I need to scan through all of the elements and do type checks.  

Could these be exposed to make this library more user-friendly?

**Comment by emicklei** [comment]
sure, we can do.  There is also a PR ready for visitors that need to track the parent for each element. Might be useful too.

**Comment by emicklei** [comment]
i am thinking about an alternative design, using the Walker,Filter pattern
```
type Filter func(v Visitee)

func WithService(apply func(*Service)) Filter {
	return func(v Visitee) {
		if s, ok := v.(*Service); ok {
			apply(s)
		}
	}
}

func Walk(proto *Proto, filters ...Filter) {
	for _, eachElement := range proto.Elements {
		for _, eachFilter := range filters {
			eachFilter(eachElement)
		}
	}
}
```
then we can have something like
```
proto.Walk(yourDefinition, WithService(handleService), WithMessage(handleMessage))
```

**Comment by emicklei** [comment]
please have a look at #63

**Comment by emicklei** [comment]
Walk is added
