### ISSUE TITLE
Add line numbers to all Visitees?

### ISSUE THREAD

**Issue by peter-edge** [emicklei/proto#7]
I'd like to write a linter based on this library, and line numbers for all Visitees would be great. I can put together a PR to this effect if this is something you'd be open to.

**Comment by emicklei** [comment]
yes sure. 

the scanner knows the line so hopefully without much effort, you could add e.g. LineNumber to each node type.

**Comment by peter-edge** [comment]
Ok great, will send you something :-)

**Comment by emicklei** [comment]
do you expect to finish this in the near future? Otherwise, I will put some time to it

**Comment by peter-edge** [comment]
One of my colleagues is almost finished on this, but has an off-by-one error https://github.com/emicklei/proto/compare/master...robbertvanginkel:linenumbers?expand=1, he should be finished with this soon

**Comment by emicklei** [comment]
Thinking about this upcoming change, what if we add the column position on the line as well.  Similar to https://golang.org/src/go/token/position.go

**Comment by peter-edge** [comment]
Hey, sorry about the delay. You may want to just continue on his work, Robbert is held up on a few things.

**Comment by robbertvanginkel** [comment]
I opened #10, which gets adds the line numbers and tests for the cases I could find. I don't plan on working on it more, not sure if its the best approach either as I'm still getting to know go as a language. I put up the pr so it can be continued/merge/closed as you see fit.

**Comment by peter-edge** [comment]
Hey @emicklei how does that look as a start? We could do column after.

**Comment by emicklei** [comment]
hi,

@robbertvanginkel , @peter-edge thank you for all this work. Quite a big effort.
I was planning to continue with the feature by replacing the LineNumbers field to a Position struct (just lik go parser is doing). I had the impression you (your team) no longer had time to work on it.

**Comment by peter-edge** [comment]
Hey,

Totally up to you! I'm hoping to have at least line numbers sooner than later, I have my own linter I need to implement (which maybe eventually I can contribute back), and I require at least line numbers for it (but column would be great too).

**Comment by emicklei** [comment]
see https://github.com/emicklei/proto/tree/linenumbers

**Comment by emicklei** [comment]
lot of work has been done ; major refactoring. I am now at the point that a few tests are failing. Hope to finish it in the next days.

**Comment by emicklei** [comment]
@peter-edge @robbertvanginkel thank you contributing. I just merged the changes
