### ISSUE TITLE
Options with only a part parenthesized isn't parsed

### ISSUE THREAD

**Issue by RangelReale** [emicklei/proto#71]
This envoyproxy .proto option gives an error when I parsed. I couldn't find whether this is allowed or but, but envoyproxy is a big project, I used their proto files are used a lot.

https://github.com/envoyproxy/data-plane-api/blob/master/envoy/api/v2/auth/cert.proto#L36

TlsProtocol tls_minimum_protocol_version = 1 [(validate.rules).enum.defined_only = true];

2018/03/14 16:34:34 Error parsing file envoy/api/v2/auth/cert.proto: <input>:36:66: found "enum" but expected [option postfix identifier]

**Comment by emicklei** [comment]
thank you for reporting this. I will include it in my tests and work on a fix

**Comment by emicklei** [comment]
I fixed the reported one but found another issue at line 115. I wonder whether the source is correct as the identifier has a whitespace between `repeated` and `.min_items`:  

```
  repeated core.DataSource keys = 1 [(validate.rules).repeated .min_items = 1];
``

**Comment by emicklei** [comment]
if this is correct then should the first option be interpreted as `(validate.rules).repeated = true` ?

**Comment by RangelReale** [comment]
These are very strange, where do people find out these weird strange cases on protobuf?
I don't really use envoy, I got this error while trying my library on all proto files I could find.
Maybe the protobuf BNF file can help?

**Comment by RangelReale** [comment]
I found these options come from here:

https://github.com/lyft/protoc-gen-validate/blob/master/validate/validate.proto

But I don't see anything different in it than in other proto files...

**Comment by emicklei** [comment]
Someone pointed me to 

https://developers.google.com/protocol-buffers/docs/reference/proto2-spec
https://developers.google.com/protocol-buffers/docs/reference/proto3-spec

it says

`fieldOption = optionName "=" constant`

Now, I am looking for the validate.proto to see it definition

**Comment by emicklei** [comment]
https://github.com/lyft/protoc-gen-validate/blob/master/validate/validate.proto

**Comment by RangelReale** [comment]
Reading more proto files, I think that the whole problem is that the options aren't a simple value, they are a full-fledged message instance, like this validation:

  string name  = 3 [(validate.rules).string = {
                      pattern:   "^[^\d\s]+( [^\d\s]+)*$",
                      max_bytes: 256,
                   }];

To support this I think you would need a big overhaul of the option parsing...

**Comment by RangelReale** [comment]
(Removed the last comment, was an error on the proto file itself.)

**Comment by RangelReale** [comment]
Other problem with this field:

    Location home = 4 [(validate.rules).message.required = true];

The parser considers "message" a reserved word, but it isn't on this context.

    2018/03/15 17:08:37 <input>:15:39: found "message" but expected [option postfix identifier]

**Comment by emicklei** [comment]
see #72 that fixes this too

**Comment by RangelReale** [comment]
Seems fine to me!
