### ISSUE TITLE
Escape sequences are being parsed inside strings

### ISSUE THREAD

**Issue by RangelReale** [emicklei/proto#73]
Another problem I found, given this definition:

    string name  = 3 [(validate.rules).string = {
                      pattern:   "^[^\d\s]+( [^\d\s]+)*$",
                      max_bytes: 256,
                   }];

The parser is trying to escape the "\d" sequence in "pattern", but I don't think it should interpret the string, shouldn't it leave this to the library user?
If I added another "\" after the other ones, then it works, but the output string has the two "\", it even doesn't remove them.

    2018/03/16 09:08:55 go scanner error at <input>:11:34 = illegal char escape
    go scanner error at <input>:11:34 = illegal char escape
    go scanner error at <input>:11:34 = illegal char escape
    go scanner error at <input>:11:34 = illegal char escape

**Comment by emicklei** [comment]
this is a challenging problem. Need to think about how to solve it. First idea, do the scanning of option content differently.

**Comment by RangelReale** [comment]
Debugging into the library, I had the impression that this is done by Go, by the Scanner interface if I'm not wrong.

**Comment by emicklei** [comment]
true, so apparently the option syntax does not conform to the Go language spec (which it should not ofcourse but saved me a lot of work, initially).

**Comment by emicklei** [comment]
i created a test for this but was surprised to see a PASS
```
func TestFieldOptionEscapeCharacters(t *testing.T) {
	src := `string name  = 3 [(validate.rules).string = {
	pattern:   "^[^\d\s]+( [^\d\s]+)*$",
	max_bytes: 256,
 }];`
	p := newParserOn(src)
	f := newNormalField()
	err := f.parse(p)
	if err != nil {
		t.Fatal(err)
	}
}
```

**Comment by emicklei** [comment]
what go sdk version are you using?

**Comment by emicklei** [comment]
so when testing the actual value in Go, I needed to escape the slashes
```
func TestFieldOptionEscapeCharacters(t *testing.T) {
	src := `string name  = 3 [(validate.rules).string = {
	pattern:   "^[^\d\s]+( [^\d\s]+)*$",
	max_bytes: 256,
 }];`
	p := newParserOn(src)
	f := newNormalField()
	err := f.parse(p)
	if err != nil {
		t.Fatal(err)
	}
	if got, want := f.Options[0].AggregatedConstants[0].Source, "^[^\\d\\s]+( [^\\d\\s]+)*$"; got != want {
		t.Errorf("got [%v] want [%v]", got, want)
	}
}
```

I think my parser is accepting it because of ```scanner.ScanRawStrings``` when initializing the scanner.

**Comment by RangelReale** [comment]
> go version
go version go1.9.2 windows/amd64

I will try on the latest version.

**Comment by RangelReale** [comment]
I had the same problem on the last version.

I am uploading my test source and file, running "go run main.go" on this directory triggers the errors I talked above.

[tstproto.zip](https://github.com/emicklei/proto/files/1819743/tstproto.zip)

**Comment by emicklei** [comment]
thanks, this indeed reproduces the problem. I will find the differences later

**Comment by emicklei** [comment]
thx, i know now why I did not see the errors before. Now I am working on a solution.

**Comment by emicklei** [comment]
see #74

**Comment by RangelReale** [comment]
Nice, thanks!

**Comment by emicklei** [comment]
can this be closed?
