### ISSUE TITLE
Enum value should accept hex numbers

### ISSUE THREAD

**Issue by RangelReale** [emicklei/proto#75]
I see a number of examples that uses hex numbers on enum values, like this post:

https://groups.google.com/forum/#!topic/protobuf/L105Q4NIk0U

The google parser acccepts it, so I think this is a supported thing.

    <input>:27:18: found "=" but expected [enum field integer]

**Comment by emicklei** [comment]
thank you for reporting this. I will create a test for it too

**Comment by RangelReale** [comment]
Tested in my application, fixed, thanks!
