### ISSUE TITLE
The new map of Literals makes iteration non-deterministic

### ISSUE THREAD

**Issue by peter-edge** [emicklei/proto#82]
I ran into this with testing.

Before, withe the AggregatedConstants, iterating over the slice would produce a deterministic ordering. Now, with the map[string]*Literal, the key:value ordering in the file is not preserved. The `Literal.Map` in #81  needs to be ordered.

**Comment by emicklei** [comment]
Can you elaborate why the ordering is important?  The tests should not depend on it.

**Comment by peter-edge** [comment]
Ordering is important for formatting. Take this example:

```
  option (foo.bar) = {
    baz: "bat"
    ban: "bam"
  };
```

If I use this library in a formatting tool, the parsed values for '(foo.bar)' will not be ordered in the map, so when I iterate over them and print out the result, I can get one of two things, either the above or:

```
  option (foo.bar) = {
    ban: "bam"
    baz: "bat"
  };
```

This means there will be thrashing in the formatted file. Users probably also want to maintain their existing ordering of values - we could do something like alphabetize them, but that's not how users would generally expect this to work, a lot of the times the ordering matches the tag numbers.

**Comment by emicklei** [comment]
I agree for the purpose of formatting. I will have a look at your PR, thanx.

**Comment by emicklei** [comment]
can this be closed?
