### ISSUE TITLE
Package name that starts with keyword cannot be parsed

### ISSUE THREAD

**Issue by peter-edge** [emicklei/proto#89]
```go
func TestNextIdentifierStartsWithKeyword(t *testing.T) {
	ident := " rpc.mies.enum ="
	p := newParserOn(ident)
	_, tok, lit := p.nextIdentifier()
	if got, want := tok, tIDENT; got != want {
		t.Errorf("got [%v] want [%v]", got, want)
	}
	if got, want := lit, "rpc.mies.enum"; got != want {
		t.Errorf("got [%v] want [%v]", got, want)
	}
	_, tok, _ = p.next()
	if got, want := tok, tEQUALS; got != want {
		t.Errorf("got [%v] want [%v]", got, want)
	}
}
```

This produces:

```
$ go test .
--- FAIL: TestNextIdentifierStartsWithKeyword (0.00s)
	parser_test.go:112: got [23] want [3]
	parser_test.go:115: got [rpc] want [rpc.mies.enum]
	parser_test.go:119: got [19] want [6]
```

This test is just the `WithKeyword` test, but starts with a keyword instead of a keyword being in the middle or at the end.

Related to #37.
See https://github.com/uber/prototool/issues/103.

**Comment by AlexAPB** [comment]
I think the fix is just changing the [package parsing](https://github.com/emicklei/proto/blob/master/package.go#L43) to use `p.nextIdent(true)`.

This test will pass if we use `p.nextIdent(true)` instead of `p.nextIdentifier()`, since the boolean enables keyword prefixes.

**Comment by peter-edge** [comment]
This is replicating the issue in Prototool - if that passes this test, then this test is not what we want. See the prototool issue for more details.

**Comment by AlexAPB** [comment]
I've used this test in verifying that the package parsing is implemented correctly, PR with fix to follow.

```go
func TestPackageParseWithReservedPrefix(t *testing.T) {
	want := "rpc.enum.oneof"
	ident := " " + want + ";"

	pkg := new(Package)
	p := newParserOn(ident)
	if err := pkg.parse(p); err != nil {
		t.Error(err)
	}

	if pkg.Name != want {
		t.Errorf("got %q want %q", pkg.Name, want)
	}
}
```
Produces:

```
--- FAIL: TestPackageParseWithReservedPrefix (0.00s)
	package_test.go:41: got "rpc" want "rpc.enum.oneof"
```

Essentially the parser stops parsing at the first reserved word (in this case `rpc`)

**Comment by emicklei** [comment]
can this be closed?
