### ISSUE TITLE
how to get the package name via `*proto.Proto`

### ISSUE THREAD

**Issue by hitzhangjie** [emicklei/proto#91]
how to get the package name via `*proto.Proto`? I think top-level descriptors should be contained in *proto.Proto.

**Comment by peter-edge** [comment]
Its in proto.Package, walk using the visitor pattern and you’ll hit one. I think this issue should be closed.

**Comment by emicklei** [comment]
alternative
```
func packageOf(def *pp.Proto) string {
	for _, each := range def.Elements {
		if p, ok := each.(*pp.Package); ok {
			return p.Name
		}
	}
	return ""
}
```
only works for valid definitions
