### ISSUE TITLE
Type that starts with dot cannot be parsed correctly

### ISSUE THREAD

**Issue by Scukerman** [emicklei/proto#92]
```go
func TestNextIdentifierStartsWithDot(t *testing.T) {
	ident := ".game.Resource ="

	p := newParserOn(ident)
	_, tok, lit := p.nextIdentifier()
	if got, want := tok, tIDENT; got != want {
		t.Errorf("got [%v] want [%v]", got, want)
	}
	if got, want := lit, ".game.Resource"; got != want {
		t.Errorf("got [%v] want [%v]", got, want)
	}
	_, tok, _ = p.next()
	if got, want := tok, tEQUALS; got != want {
		t.Errorf("got [%v] want [%v]", got, want)
	}
}
```

The test output:
```
--- FAIL: TestNextIdentifierStartsWithDot (0.00s)
        message_test.go:178: got [19] want [3]
        message_test.go:181: got [.] want [.game.Resource]
        message_test.go:185: got [3] want [6]
FAIL
exit status 1
FAIL    github.com/emicklei/proto       0.014s
```

See: https://github.com/uber/prototool/issues/235

**Comment by emicklei** [comment]
According to the specs, an identifier must start with a letter.
See https://developers.google.com/protocol-buffers/docs/reference/proto3-spec

Does protoc except this?

**Comment by peter-edge** [comment]
The spec they have here is valid, it’s a fully-qualified name - in the
Prototool issue they linked, there’s a link that describes it. But tldr you
can start paths with ‘.’

**Comment by emicklei** [comment]
@Scukerman I have read the "Packages and Name Resolution" section and understand that a leading dot is valid for this purpose. The proposed unit test is not correct as I do not want to change the nextIdentifier(). I will create a new one and provide the fix.

**Comment by Scukerman** [comment]
Of course. I knew I might be wrong when test was written.
Thanks a lot.

BTW, I also didn't see the explanation of this issue in the syntax spec. Why so?
