### ISSUE TITLE
ignoring single-quoted reserved field names 

### ISSUE THREAD

**Issue by nilslice** [emicklei/proto#94]
```go
func TestReservedFieldNamesSingleQuote(t *testing.T) {
	r := new(Reserved)
	p := newParserOn(`reserved 'foo', 'bar';`)
	_, _, _ = p.next()
	err := r.parse(p)
	if err != nil {
		t.Fatal(err)
	}
	if got, want := len(r.FieldNames), 2; got != want {
		t.Fatalf("got [%v] want [%v]", got, want)
	}
	if got, want := r.FieldNames[0], "'foo'"; got != want {
		t.Errorf("got [%v] want [%v]", got, want)
	}
	if got, want := r.FieldNames[1], "'bar'"; got != want {
		t.Errorf("got [%v] want [%v]", got, want)
	}
}
```

I'm not certain about the expected `"'bar'"` or `"'foo'"` literals in the test, but the `len(r.FieldNames)` should be 2. 

This is in reference to a user report from one of my repos: https://github.com/nilslice/protolock/issues/65

**Comment by nilslice** [comment]
My PR (#95) seems to make the reserved w/ single-quote test pass, but when actually parsing a full message, I get this failure from the `scanner` pkg: 
```
go scanner error at <input>:7:12 = illegal char literal        
go scanner error at <input>:7:21 = illegal char literal        
go scanner error at <input>:8:20 = illegal char literal
```

The message in question is:
```protobuf

syntax = "proto3";

package test;

message Channel {
  reserved 'thing', 'another';
  reserved "more", 'mixed';
  int64 id = 1;
  string name = 2;
  string description = 3;
}
```

**Comment by emicklei** [comment]
thank you for reporting this issue. 

I verified that single quote string are indeed allowed.
```strLit = ( "'" { charValue } "'" ) |  ( '"' { charValue } '"' )```

However, the proto parser uses the standard Go scanner which does not accept it (illegal rune literal) so now I have to think about how to deal with that.

Ofcourse, the workaround is not using the single quotes for now.

**Comment by emicklei** [comment]
the parser is not (completely) validating the proto file so empty reserved names should not be ignored. Tools such as protolint and protoc will.
Please have a look at PR #96 which uses your fix to add a scanner mode and adds your message test.

**Comment by nilslice** [comment]
> the parser is not (completely) validating the proto file so empty reserved names should not be ignored. Tools such as protolint and protoc will.

makes sense -- great callout. 

> Please have a look at PR #96 which uses your fix to add a scanner mode and adds your message test.

I will run through the test and build my tool against this version and try it out. Thanks!
