### ISSUE TITLE
Unable to parse messages like .google.protobuf.Empty

### ISSUE THREAD

**Issue by anujdecoder** [emicklei/proto#97]
**I've used the source code given in readme on the following test.proto:**
syntax = "proto3";

package appointy.go.program;

import "google/protobuf/empty.proto";
option go_package = "go.appointy.com/google/pb/program";

service Programs {
    rpc AddProgram (Program) returns (ProgramIdentifier) {
        
    }

    rpc GetProgram (ProgramIdentifier) returns (Program) {
        
    }

    rpc DeleteProgram (ProgramIdentifier) returns (.google.protobuf.Empty) {
        
    }
}

message Program {
    string id = 1;
    string title = 2;
    string description = 3;
    string logo_url = 4;
    string slug = 5;
    string type = 6;
    map<string, string> metadata = 7;
    bool is_active =8;
}

message ProgramIdentifier {
    string id = 1;
}

The **error I encountered** is :
<input>:17:52: found "." but expected [rpc stream | returns type]

**Comment by emicklei** [comment]
thank for reporting this. I created a branch that solves, issue97

**Comment by emicklei** [comment]
#98

**Comment by emicklei** [comment]
see tag v1.6.7
