### ISSUE TITLE
unable to parse option name with leading dot

### ISSUE THREAD

**Issue by aroch** [emicklei/proto#99]
I've run the example program on a .proto file which includes a Field Option which has a leading '.' and I see that the message is not getting parsed.
I get the error:
```
<input>:23:35: found "." but expected [option full identifier]
```
We use the leading '.' to start the name resolution from the outermost scope.

Example:
```
string app_entity_id = 4 [(.common.v1.some_custom_option) = { opt1: true opt2: false }];
```
Similar to #97

**Comment by emicklei** [comment]
i will create a test for this and fix it. I plan to include this in the issue97 branch

**Comment by emicklei** [comment]
see tag v1.6.7
